### ISSUE TITLE
1 秒之后 readAll

### ISSUE THREAD

**Issue by StrangeTown** [ilvseyinfu/email_web#2]
哥们，万一 db 的连接大于 1 秒呢

**Comment by ilvseyinfu** [comment]
因为所有操作都是异步的，所以我需要用setTimeout去模拟用户等待操作，真实的生产环境当然不需要考虑这个问题，一般来说，1s中足够db连接成功，如果超过1s，this.db_person为空，也只会影响到默认数据尚未添加
